### ISSUE TITLE
Unable to connect (timeout)

### ISSUE THREAD

**Issue by LauLaman** [CppBunny/unifi_sms_gateway#1]
Hi thanks for this script and your time and effort

unfortunately for me it is not working.

[This part][code] times out:

```sh
ssh -y root@$(cat /var/run/topipv6)
```

Since you got this working, can you confirm it still does on the latest FW? (i've got the [latest][latest-fw] `6.6.57` with `BusyBox v1.25.1` installed)

Or are there additional steps that i'am missing?

My steps:
- installed new device
- added activated ISP sim (Odido)
- provisioned device
  - as part of the provisioning device got updated to the [latest FW][latest-fw]
- Got Ip, user, pass from the Uinifi network controller
- confirmed i can manually ssh in to the device

Trouble shouting steps:
- Manually ssh into device
- Brought USB up with `ifconfig usb0 up`
- Tried to ssh into the usb with `ssh -y root@$(cat /var/run/topipv6)`
- Got an timeout:
```sh
ssh: Connection to root@<redacted>%usb0:22 exited: Connect failed: Operation timed out
```

[code]: https://github.com/CppBunny/unifi_sms_gateway/blob/main/sms.py#L21C52-L21C88
[latest-fw]: https://community.ui.com/releases/r/lte/6.6.57

**Comment by CppBunny** [comment]
Hi,

It seems to be working for me. I did also have this issue a while ago but fixed it by simply rebooting the LTE Pro, let me know if that works!

**Comment by LauLaman** [comment]
A reboot of the U-LTE-Pro worked.😅

Classic example of 
![it-dep](https://github.com/CppBunny/unifi_sms_gateway/assets/8283992/10d47a94-ec9a-401f-a0b1-2027e86f97ff)
